### ISSUE TITLE
Mod Description Features

### ISSUE THREAD

**Issue by refringe** [sp-tarkov/forge#34]
Implement ways for user provided content, like mod descriptions, to be edited similar to the Hub.

# Requirements:

- [x] Standard Markdown (#183)
- [x] Tabs (#183)
- [x] Self-hyperlinks (link to a specific header on a specific tab) (#183)
- [x] Embed videos and images from sources such as Youtube or Imgur (#183)
- [x] Pre-styled information, warning, error, and success content boxes
- [ ] Pre-styled colored text options
- [x] Variations in text size (#183)
- [x] Underlining, bold, italic (#183)
- [ ] Center, left and right alignments
- [ ] Spoiler tags

**Comment by CWXDEV** [comment]
currently i have some custom html and js that lets me have a image slider type deal

https://hub.sp-tarkov.com/files/file/2010-cwx-megamod
-> GrassCutter in the tabs

might be a nice addition for graphical mods etc.

also maybe carousel?

**Comment by refringe** [comment]
Issues found with import/description support:

Before:
https://hub.sp-tarkov.com/files/file/2836-sptarkovammocraft/

After:
https://forge.sp-tarkov.com/mod/8693455/sptarkovammocraft

- Images not brought across
- Code block not brought across
